services:
  # Our PostgreSQL database
  db:
    # Using the latest PostgreSQL image
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres

  # Backend
  backend:
    build: .
    container_name: blog-backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
